language: cpp
compiler:
  - gcc
#- clang

os:
  - linux
#  - osx

addons:
  apt:
    sources:
      - george-edison55-trusty-backports
    packages:
      - cmake
      - cmake-data

dist: trusty

# not container-based
sudo: required

env:
  matrix:
    - DRAT_CONFIG=ZLIB
    - DRAT_CONFIG=NOZLIB
    - DRAT_CONFIG=INTREE_BUILD

before_install:
  - sudo apt-get update
  - sudo apt-get install software-properties-common
  - cmake --version
  - wget http://www.cmake.org/files/v3.4/cmake-3.4.1.tar.gz
  - tar -xzf cmake-3.4.1.tar.gz
  - cd cmake-3.4.1/
  - ./configure
  - make
  - sudo make install
  - sudo update-alternatives --install /usr/bin/cmake cmake /usr/local/bin/cmake 1 --force
  - cmake --version

install:
  - sudo apt-get install -y --force-yes libboost-test-dev
  - sudo apt-get install -y --force-yes cmake valgrind swig3.0
  - sudo apt-get install -y zlib1g-dev
#bulid dir
  - mkdir -p build

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./scripts/travis-cmake.sh ; fi
