language: cpp
compiler:
  - gcc
#- clang

os:
  - linux
#  - osx

dist: trusty

# not container-based
sudo: required

env:
  matrix:
    - DRAT_CONFIG=ZLIB
    - DRAT_CONFIG=NOZLIB
    - DRAT_CONFIG=INTREE_BUILD

before_install:
    - sudo apt-get -y update
    - sudo apt-get -y install language-pack-en-base
    - sudo dpkg-reconfigure locales
    - sudo apt-get -y install software-properties-common

    #- sudo add-apt-repository "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main"
    #- wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo apt-get -y update
    #- sudo apt-get -y install llvm-3.7-dev

    - sudo apt-get -y update
    - sudo apt-get -y install build-essential git cmake

install:
  - sudo apt-get install -y --force-yes libboost-test-dev
  - sudo apt-get install -y --force-yes cmake valgrind swig3.0
  - sudo apt-get install -y zlib1g-dev
#bulid dir
  - mkdir -p build

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./scripts/travis-cmake.sh ; fi
